baseURL: https://uthark.github.io
disablePathToLower: true
languageCode: en-us

title: Sharing knowledge

theme: uthark

paginate: 5

pygmentsOptions: [linenos]
# Highlight shortcode and code fences (```) will be treated similarly
pygmentsCodefences: true

# Set to true to try to do syntax highlighting on code fenced blocks in markdown
#  without a language tag.
pygmentsCodefencesGuessSyntax: true

pygmentsUseClasses: true

pygmentsUseClassic: false

params:
  subtitle: by Oleg Atamanenko
  github : "https://github.com/uthark/"
  bitbucket : "https://bitbucket.org/uthark/"
  keybase : "https://keybase.io/uthark/"
  stackoverflow: "http://stackoverflow.com/users/216764/uthark"

  # If false, all of blog post will appear on front page (and in pagination)
  truncate : true
  author: Oleg Atamanenko
  # Switch to true to enable RSS icon link
  textrss: true
  rss : true
  customRSSURL: https://feeds.feedburner.com/atamanenko

  # Search engine URL
  searchEngineURL : "https://www.google.com/search"
  sidebarMenuEnabled: false
  sidebarMenuHeader: "Sidebar"
  disableReadingTime: false

  googleAnalytics: UA-8688665-1

  twitter:
    url: "https://twitter.com/real_atamanenko"
    card: "summary"
    site: "@real_atamanenko"
    creator: "@real_atamanenko"

menu:
  main:
    - Name: "Posts"
      URL: "/"
      weight: -5
    - Name: "Reading Lists"
      URL: "/readinglist/"
      weight: -1
    - Name: "Categories"
      URL: "/categories/"
      weight: -2
    - Name: "Links"
      URL: "/usefularticles/"
      weight: -3
    - Name: "About"
      URL: "/about/"
      weight: 0

taxonomies:
  tag: "tags"
  category: "categories"

blackfriday:
  hrefTargetBlank: true
# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]
#  sidebar:
#    - Name: "Home"
#      URL: "/"
#      weight: 0
#    - Name: "Articles"
#      URL: "/categories/article/"
#      weight: 2
#    - Name: "Reading List"
#      URL: "/categories/reading-list/"
#      weight: 1

disqusShortname: "uthark"
